spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  graphql:
    graphiql:
      enabled: true
    cors:
      allowed-origins: "*"
    schema:
      printer:
        enabled: true
      file-extensions: .graphql
